In [1]:
# this is the code for 8 queen Dynamic programming problem.

In [2]:
# importing all the required libraries
import numpy as np

In [3]:
# board state memory
board_state_memory:dict = {}

In [4]:
N = 8

# creating an N * N board
board = np.zeros((N, N), np.int8)

In [5]:
board

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [6]:
# create board string
def create_board_string(board):
    board_string = ''
    for i in range(N):
        for j in range(N):
            board_string += str(board[i][j])
    return board_string

In [7]:
# testing the Create_board_string function
create_board_string(board)

'0000000000000000000000000000000000000000000000000000000000000000'

In [8]:
# copying the board and positioning the queen at 1 column, 1 row
board_copy = board.copy()
board_copy[0, 1] = 1

In [9]:
board_copy
create_board_string(board_copy)

'0100000000000000000000000000000000000000000000000000000000000000'

In [10]:
def is_board_safe(board):
    
    #This is where the dynaic programming comes into picture. Where we use the board_state_memory to cache.
    board_key = create_board_string(board)
    
    if board_key in board_state_memory:
        print('Using Cached Information')
        return board_state_memory[board_key]
    
    # calculate the sum in every row of the board
    row_sum = np.sum(board, axis = 1)
    # checking if a row has more than 1 queen - we will check the sum or elements in a row
    if len(row_sum[np.where(row_sum > 1)]) > 0:
        board_state_memory[board_key] = False
        return False
    
    # checking column sum in every row of the board
    col_sum = np.sum(board, axis = 0)
    if len(col_sum[np.where(col_sum > 1)]) > 0:
        board_state_memory[board_key] = False
        return False
    
    diags = [board[::-1,:].diagonal(i) for i in range(-board.shape[0] + 1, board.shape[1])]
    
    diags.extend(board.diagonal(i) for i in range(board.shape[1] - 1, -board.shape[0], -1))
    
    for diag in diags:
        if np.sum(diag) > 1:
            board_state_memory[board_key] = False
            return False
        
    board_state_memory[board_key] = True
    return True

In [11]:
board_copy = board.copy()
board_copy[1][0] = 1
board_copy[2][3] = 1
board_copy[0][1] = 1

In [12]:
print(board_copy)
is_board_safe(board_copy)

[[0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


False

In [13]:
# defining the placing of the Queen 

def place_queen_safely(board, column):
    
    if column >= N:
        # All N queens are placed correctly
        return True
    
    for row in range(N):
        board[row][column] = 1
        
        safe = False
        
        if is_board_safe(board):
            safe = place_queen_safely(board, column + 1)
    
        if not safe:
            board[row][column] = 0
            
        else: 
            break
    return safe
    

In [14]:
board_state_memory

{'0100000010000000000100000000000000000000000000000000000000000000': False}

In [15]:
board = np.zeros((N,N), np.int8)
placed = place_queen_safely(board, 0)
print(board)

[[1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]]


In [16]:
placed
# just checking if everything is set.

True


Q-learning and SARSA in Reinforcement Learning.
Q-learning gives us the optimal policy to maximize the returns in a Reinforcement learning.

Agent observes the environment and takes actions based on a policy.
The output of reinforcement learning is a set of actions which maximize the cumulative rewards.

Policy Search algorithms
1. Brute Force methods
2. Policy Gradient methods
3. Value Function metods

Value Function methods are most common

Q-learning techniques (Temporal difference)
SARSA method (Another implementation of Q-learning)

# Test Case is a student deciding whether to enroll in further studies or start the first job.
Agent here is the person (an undergraduate)
Reward is the cumulative savings in money by the age of 60 years.
Policy is the algorithm that chooses either of the two steps(enroll in further studies or Starting first jobs) that gives maximum rewards.

Any state could be define as follows
(<State of the plan to further studies>,<Years of Experience in the job>)
    
Initial State is (BS-EE, 0) # Bachelors in Electrical Engineering, 0 years of work experience
If Action = further Studies
    Next State = (MS-CS, 0) # Masters in Computers, 0 years of work experience
Else:
    Next State = (BS-EE, 2) # If she/he didn't choose further studies, then 2 years of work experience will be earned.
    
# Q-Learning is a Value Function policy
# Estimate rewards at the Terminal (Destination, Final positions) and probabilities of getting there, then work backwards.

Once the total path is ready, we calculate the probabilities and rewards at each state. Also, the penalty i.e., the cost of education is to be considered.

At the first step, when we calculate rewards - penalties, we end up with the amounts which determine the immediate decision to take.

# Q-Learning and SARSA: Maximize the sum of immediate reward and discounted future reward.

Steps in implementing a Q-Learning
1. Set up a Q-Table for every state-action combination. Rows form the states and Columns form the actions.
2. Q-value is the estimate of optimal state value. Q-Value helps the agent in taking decisions.
3. What is a Q-value: If we take an action from State S, the cumulative long run reward is called as Q-Value.
   it is represented by Q(s, a)
   At a particular state, we choose the maximum Q-Value to take a particular action, as it maximizes the reward.
   
# Different methods can be used to calculate the Q-Values.
# Temporal difference and SARSA are the different ways in which the Q-Values can be calculated. Temporal difference is nothing but Q-Learning. SARSA is another verion of it.

# Temporal Difference Notes - Refer image.
    